apiVersion: apps/v1
kind: Deployment
metadata:
  name: dml-h5
  namespace: default
spec:
  selector:
    matchLabels:
      app: dml-h5
  template:
    metadata:
      labels:
        app: dml-h5
    spec:
      containers:
      - image: weichuanbo/dml-h5:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: dml-h5
        env:
        - name: branch
          value: <BRANCH_NAME>
